// tgd-reviews.js — Avis Google live + transformation B2B homepage
(function(){
'use strict';
const FALLBACK=[
{author:'Florent Vial',rating:5,text:"Yvan a été d'un grand professionnalisme lors de la livraison de mon véhicule ! Très agréable, disponible et soucieux de m'expliquer les choses en prenant le temps !",publishedAt:'2026-05-19T00:00:00Z'},
{author:'Cédric Niçoise',rating:5,text:"Livraison du véhicule parfaite : une entreprise sérieuse, ponctuelle et d'un professionnalisme irréprochable.",publishedAt:'2026-04-15T00:00:00Z'},
{author:'Frédéric Bazin',rating:5,text:"C'est le deuxième véhicule BMW que Jonathan me livre. Merci à lui pour ces précieux conseils. Le service est à la hauteur de la marque.",publishedAt:'2026-03-23T00:00:00Z'}
];
const esc=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');
const ts=r=>{const v=Date.parse(r?.publishedAt||r?.updateTime||r?.createTime||r?.date||'');return Number.isFinite(v)?v:0};
const norm=r=>({author:r.author||r.authorName||r.reviewer||'Client Google',rating:Number(r.rating)||5,text:r.text||r.comment||r.reviewText||'',publishedAt:r.publishedAt||r.updateTime||r.createTime||r.date||null});
const stars=n=>'★'.repeat(Math.max(0,Math.min(5,Number(n)||0)))+'☆'.repeat(5-Math.max(0,Math.min(5,Number(n)||0)));
function date(r){const v=ts(r);return v?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v)):'Avis Google'}
function card(r){r=norm(r);return `<div class="testi"><div class="testi-stars">${stars(r.rating)}</div>${r.text?`<p class="testi-quote">« ${esc(r.text)} »</p>`:''}<div class="testi-author">${esc(r.author)}</div><div class="testi-role">${esc(date(r))} · Google</div></div>`}
function render(w,reviews,rating,total){const ordered=(reviews||[]).map(norm).sort((a,b)=>ts(b)-ts(a));w.forEach(x=>{const m=Math.max(1,parseInt(x.dataset.max||'3',10));x.innerHTML=ordered.slice(0,m).map(card).join('')});const sr=Number(rating)||5,st=Number(total)||38;document.querySelectorAll('.tgd-rating-score').forEach(e=>e.textContent=sr.toFixed(1).replace('.',','));document.querySelectorAll('.tgd-rating-total').forEach(e=>e.textContent=`${st} avis`);document.querySelectorAll('.tgd-rating-number').forEach(e=>e.textContent=String(st))}
function upgradeHome(){
 if(!document.body.classList.contains('site-home'))return;
 document.querySelectorAll('.nav-links a[href="/entreprises"],.mobile-menu a[href="/entreprises"]').forEach(a=>{a.href='/solutions-professionnelles';a.textContent='Solutions Pro'});
 const hero=document.querySelector('.hero');
 if(hero){
   const eyebrow=hero.querySelector('.eyebrow'); if(eyebrow)eyebrow.textContent='Automotive Mobility Operations · France & Europe';
   const h1=hero.querySelector('h1'); if(h1)h1.innerHTML='Pas seulement transporté.<br><em>Piloté de bout en bout.</em>';
   const desc=hero.querySelector('.hero-desc'); if(desc)desc.innerHTML='Convoyage, livraison client, mise en main, mouvements de flotte et traçabilité digitale. <strong style="color:#f5f0e8;font-weight:500">Un interlocuteur. Une exécution terrain. Une preuve à chaque étape.</strong>';
   const actions=hero.querySelector('.hero-actions'); if(actions)actions.innerHTML='<a href="/solutions-professionnelles" class="btn-primary">Découvrir les solutions pro</a><a href="#devis-express" class="btn-ghost">Confier une mission</a>';
   if(!hero.querySelector('.tgd-hero-promise')){const p=document.createElement('div');p.className='tgd-hero-promise';p.innerHTML='<span>Mission affectée ≠ mission pilotée</span><strong>TGD prend la responsabilité opérationnelle du mouvement jusqu’à la remise des clés.</strong>';hero.querySelector('.hero-left')?.appendChild(p)}
 }
 const pro=document.querySelector('.audience-card[data-audience="professionnel"]'); if(pro){pro.href='/solutions-professionnelles';const s=pro.querySelector('strong');if(s)s.textContent='Je gère des véhicules professionnels';const c=pro.querySelector('strong + span');if(c)c.textContent='Flottes, constructeurs, groupes automobiles, concessions et opérations digitales.'}
 if(!document.getElementById('tgd-home-machine-style')){
  const st=document.createElement('style');st.id='tgd-home-machine-style';st.textContent=`
  .site-home .hero{background:radial-gradient(circle at 72% 32%,rgba(143,156,169,.12),transparent 32%),linear-gradient(135deg,#08090b 0%,#0c0f13 55%,#111820 100%)!important;border-bottom:1px solid rgba(201,169,110,.16)}
  .site-home .hero-left::after{background:linear-gradient(to bottom,transparent,rgba(201,169,110,.5),transparent)!important}
  .site-home .hero-right{background:linear-gradient(145deg,#151b22,#0b0e12)!important}
  .site-home .hero h1{font-size:clamp(3.2rem,5.3vw,5.7rem)!important;max-width:780px}
  .site-home .hero-desc{font-size:1rem!important;max-width:650px!important}
  .tgd-hero-promise{margin-top:1.25rem;padding-top:1rem;border-top:1px solid rgba(159,169,180,.18);max-width:650px;display:flex;gap:1rem;align-items:flex-start}.tgd-hero-promise span{font-size:.62rem;letter-spacing:.14em;text-transform:uppercase;color:#c9a96e;white-space:nowrap}.tgd-hero-promise strong{font-size:.72rem;line-height:1.55;color:#aeb6bd;font-weight:400}
  #tgd-b2b-home-hub{padding:3.3rem 4vw!important;background:#0b0e12;border-bottom:1px solid rgba(201,169,110,.15)}
  #tgd-b2b-home-hub .inner{max-width:1180px;margin:auto}.b2b-head{display:flex;justify-content:space-between;gap:2rem;align-items:end;margin-bottom:1.6rem}.b2b-head h2{font-family:'Cormorant Garamond',serif;font-weight:300;font-size:clamp(2.2rem,4vw,3.8rem);line-height:1.05;margin:0}.b2b-head h2 em{color:#c9a96e}.b2b-head p{max-width:500px;color:#9fa8b1;font-size:.78rem;margin:0}.b2b-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.b2b-card{background:linear-gradient(145deg,#151a20,#0f1318);border:1px solid rgba(157,169,180,.16);padding:1.8rem;text-decoration:none;min-height:220px;position:relative;transition:.25s}.b2b-card:hover{transform:translateY(-3px);border-color:rgba(201,169,110,.55)}.b2b-card .code{font-size:.62rem;letter-spacing:.2em;text-transform:uppercase;color:#8f9aa4}.b2b-card h3{font-family:'Cormorant Garamond',serif;font-size:1.9rem;font-weight:400;margin:.8rem 0;color:#f5f0e8}.b2b-card h3 em{color:#c9a96e}.b2b-card p{font-size:.75rem;color:#aeb6bd;line-height:1.7;margin:0 0 1rem}.b2b-card .go{position:absolute;bottom:1.35rem;left:1.8rem;font-size:.64rem;letter-spacing:.14em;text-transform:uppercase;color:#c9a96e}.b2b-proof{display:grid;grid-template-columns:repeat(4,1fr);margin-top:1rem;gap:1px;background:rgba(201,169,110,.12)}.b2b-proof div{background:#101419;padding:1rem 1.2rem}.b2b-proof strong{display:block;font-family:'Cormorant Garamond',serif;font-size:1.55rem;color:#f5f0e8;font-weight:400}.b2b-proof span{font-size:.62rem;letter-spacing:.1em;text-transform:uppercase;color:#8f9aa4}
  #tgd-control-layer{padding:4rem 4vw!important;background:#090b0e;border-top:1px solid rgba(159,169,180,.12);border-bottom:1px solid rgba(201,169,110,.12)}#tgd-control-layer .inner{max-width:1180px;margin:auto}.control-head{display:grid;grid-template-columns:1fr 1fr;gap:3rem;align-items:end;margin-bottom:2rem}.control-head h2{font-family:'Cormorant Garamond',serif;font-weight:300;font-size:clamp(2.3rem,4vw,4rem);line-height:1.05;margin:0}.control-head h2 em{color:#c9a96e}.control-head p{color:#aeb6bd;font-size:.8rem;line-height:1.8;margin:0}.control-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:rgba(159,169,180,.16)}.control-item{background:#11161c;padding:1.45rem 1.2rem;min-height:190px}.control-item .num{font-size:.62rem;letter-spacing:.18em;color:#c9a96e}.control-item h3{font-family:'Cormorant Garamond',serif;font-size:1.3rem;font-weight:400;margin:.65rem 0;color:#f5f0e8}.control-item p{font-size:.7rem;line-height:1.65;color:#9fa8b1}.control-line{margin-top:1rem;padding:1.2rem 1.4rem;border:1px solid rgba(201,169,110,.16);display:flex;justify-content:space-between;gap:1rem;align-items:center;background:linear-gradient(90deg,rgba(201,169,110,.05),rgba(159,169,180,.04))}.control-line strong{font-family:'Cormorant Garamond',serif;font-size:1.4rem;font-weight:400}.control-line span{font-size:.66rem;color:#c9a96e;letter-spacing:.12em;text-transform:uppercase}
  #tgd-digital-proof{padding:3.8rem 4vw!important;background:#101419;border-bottom:1px solid rgba(201,169,110,.12)}#tgd-digital-proof .inner{max-width:1180px;margin:auto;display:grid;grid-template-columns:.9fr 1.1fr;gap:3rem;align-items:center}.digital-copy h2{font-family:'Cormorant Garamond',serif;font-size:clamp(2.2rem,4vw,3.6rem);font-weight:300;line-height:1.08;margin:.4rem 0 1rem}.digital-copy h2 em{color:#c9a96e}.digital-copy p{color:#aeb6bd;font-size:.8rem;line-height:1.8}.digital-screen{border:1px solid rgba(159,169,179,.2);background:#0b0e12;padding:1rem;box-shadow:0 18px 50px rgba(0,0,0,.22)}.digital-row{display:flex;justify-content:space-between;gap:1rem;padding:.9rem;border-bottom:1px solid rgba(159,169,179,.12)}.digital-row:last-child{border:0}.digital-row strong{font-size:.75rem;color:#f5f0e8}.digital-row span{font-size:.65rem;color:#c9a96e;text-transform:uppercase;letter-spacing:.08em}
  @media(max-width:900px){.b2b-head{display:block}.b2b-head p{margin-top:1rem}.b2b-grid{grid-template-columns:1fr}.b2b-proof{grid-template-columns:1fr 1fr}#tgd-digital-proof .inner,.control-head{grid-template-columns:1fr}.control-grid{grid-template-columns:1fr 1fr}.site-home .hero h1{font-size:clamp(2.6rem,12vw,4.2rem)!important}.tgd-hero-promise{display:block}.tgd-hero-promise strong{display:block;margin-top:.45rem}}
  @media(max-width:560px){.control-grid{grid-template-columns:1fr}.control-line{display:block}.control-line span{display:block;margin-top:.5rem}}
  `;document.head.appendChild(st)
 }
 const router=document.querySelector('.audience-router');
 if(router&&!document.getElementById('tgd-b2b-home-hub')){
  const hub=document.createElement('section');hub.id='tgd-b2b-home-hub';hub.innerHTML=`<div class="inner"><div class="b2b-head"><div><div class="section-eyebrow">Solutions professionnelles</div><h2>Un opérateur.<br><em>Trois expertises.</em></h2></div><p>Pour les entreprises, flottes, constructeurs, importateurs, groupes automobiles et concessions qui veulent une exécution terrain premium avec une traçabilité exploitable.</p></div><div class="b2b-grid"><a class="b2b-card" href="/tgd-fleet"><div class="code">TGD / 01</div><h3>TGD <em>Fleet</em></h3><p>Mouvements de parc, livraison collaborateurs, départs salariés, restitutions LLD et transferts inter-sites.</p><span class="go">Découvrir Fleet →</span></a><a class="b2b-card" href="/tgd-automotive"><div class="code">TGD / 02</div><h3>TGD <em>Automotive</em></h3><p>Convoyage réseau, livraison client final, mise en main, VE et opérations constructeurs.</p><span class="go">Découvrir Automotive →</span></a><a class="b2b-card" href="/tgd-digital"><div class="code">TGD / 03</div><h3>TGD <em>Digital</em></h3><p>EDL, photos, kilométrage, batterie ou carburant, signatures, rapport PDF et historique.</p><span class="go">Découvrir Digital →</span></a></div><div class="b2b-proof"><div><strong>1,2M+</strong><span>km parcourus</span></div><div><strong>5★</strong><span>Google</span></div><div><strong>7j/7</strong><span>opérations</span></div><div><strong>FR + EU</strong><span>couverture</span></div></div></div>`;router.insertAdjacentElement('afterend',hub)
  const control=document.createElement('section');control.id='tgd-control-layer';control.innerHTML=`<div class="inner"><div class="control-head"><div><div class="section-eyebrow">La différence TGD</div><h2>Une mission n’est pas juste affectée.<br><em>Elle est maîtrisée.</em></h2></div><p>Le déplacement n’est qu’une partie de la prestation. TGD encadre ce qui se passe avant, pendant et après : contrôle du véhicule, consignes, preuves, restitution et dossier final.</p></div><div class="control-grid"><div class="control-item"><div class="num">01 · CADRAGE</div><h3>Mission qualifiée</h3><p>Adresse, contact, véhicule, énergie, contraintes et consignes sont structurés avant l’exécution.</p></div><div class="control-item"><div class="num">02 · PRISE EN CHARGE</div><h3>État documenté</h3><p>État des lieux, photos, kilométrage, carburant ou batterie et identité du véhicule.</p></div><div class="control-item"><div class="num">03 · OPÉRATION</div><h3>Pilotage terrain</h3><p>Le mouvement est suivi comme une opération, avec un interlocuteur TGD en cas d’aléa.</p></div><div class="control-item"><div class="num">04 · REMISE</div><h3>Livraison maîtrisée</h3><p>Contrôle d’arrivée, réceptionnaire identifié et signature de remise du véhicule.</p></div><div class="control-item"><div class="num">05 · PREUVE</div><h3>Dossier final</h3><p>Les éléments de mission sont consolidés pour produire une trace exploitable et partageable.</p></div></div><div class="control-line"><strong>Le conducteur exécute. TGD orchestre l’opération.</strong><span>Qualité · Traçabilité · Responsabilité opérationnelle</span></div></div>`;hub.insertAdjacentElement('afterend',control)
  const dig=document.createElement('section');dig.id='tgd-digital-proof';dig.innerHTML=`<div class="inner"><div class="digital-copy"><div class="section-eyebrow">TGD Digital</div><h2>La qualité terrain devient <em>visible.</em></h2><p>Chaque mission produit un dossier exploitable : état du véhicule, photos, kilométrage, niveau d’énergie, signatures et rapport final. Pour un Fleet Manager ou un directeur réseau, la prestation ne repose plus seulement sur une promesse.</p><a href="/tgd-digital" class="btn-ghost" style="margin-top:1rem">Voir TGD Digital</a></div><div class="digital-screen"><div class="digital-row"><strong>Mission #TGD-02641 · Paris → Lyon</strong><span>Livrée</span></div><div class="digital-row"><strong>État des lieux départ · photos · km</strong><span>Validé</span></div><div class="digital-row"><strong>Niveau carburant / batterie</strong><span>Contrôlé</span></div><div class="digital-row"><strong>Réceptionnaire · signature</strong><span>Signé</span></div><div class="digital-row"><strong>Rapport PDF</strong><span>Disponible</span></div></div></div>`;control.insertAdjacentElement('afterend',dig)
 }
}
async function load(){upgradeHome();const w=document.querySelectorAll('.tgd-reviews-widget'),d=document.querySelectorAll('.tgd-rating-total,.tgd-rating-number,.tgd-rating-score');if(!w.length&&!d.length)return;try{const r=await fetch('/api/reviews',{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();render(w,Array.isArray(x.reviews)&&x.reviews.length?x.reviews:FALLBACK,x.rating,x.total)}catch(e){render(w,FALLBACK,5,38)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();