// TGD — avis Google, navigation globale et harmonisation de la homepage
(function(){
'use strict';
const FALLBACK=[
 {author:'Théo Launay',rating:5,text:"Mon véhicule m’a été livré par Jonathan. Très sympathique et professionnel, tout s’est parfaitement déroulé, je recommande à 100% !",publishedAt:'2026-06-30T13:06:46Z'},
 {author:'Florent Vial',rating:5,text:"Yvan a été d'un grand professionnalisme lors de la livraison de mon véhicule ! Très agréable, disponible et soucieux de m'expliquer les choses en prenant le temps !",publishedAt:'2026-05-19T20:01:25Z'},
 {author:'Frédéric Bazin',rating:5,text:"C'est le deuxième véhicule BMW que Jonathan me livre. Merci à lui pour ces précieux conseils. Le service est à la hauteur de la marque.",publishedAt:'2026-03-23T15:56:18Z'},
 {author:'Isabelle NDOYE Maddio',rating:5,text:'Super moment passé avec Jonathan ! La livraison de mon nouveau véhicule a été impeccable et soignée.',publishedAt:'2026-03-18T16:15:46Z'},
 {author:'Katia Pariente',rating:5,text:'Service de convoyage automobile impeccable entre Paris et Marseille. Prise en charge simple, échanges fluides et respect des délais.',publishedAt:'2026-02-09T18:51:21Z'}
];
const esc=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const ts=r=>{const v=Date.parse(r?.publishedAt||r?.updateTime||r?.createTime||r?.date||'');return Number.isFinite(v)?v:0};
const norm=r=>({author:r.author||r.authorName||r.reviewer||'Client Google',rating:Number(r.rating)||5,text:r.text||r.comment||r.reviewText||'',publishedAt:r.publishedAt||r.updateTime||r.createTime||r.date||null});
const stars=n=>'★'.repeat(Math.max(0,Math.min(5,Number(n)||0)))+'☆'.repeat(5-Math.max(0,Math.min(5,Number(n)||0)));
function date(r){const v=ts(r);return v?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(new Date(v)):'Avis Google'}
function card(r){r=norm(r);return `<div class="testi"><div class="testi-stars">${stars(r.rating)}</div>${r.text?`<p class="testi-quote">« ${esc(r.text)} »</p>`:''}<div class="testi-author">${esc(r.author)}</div><div class="testi-role">${esc(date(r))} · Google</div></div>`}
function render(w,reviews,rating,total){const ordered=(reviews||[]).map(norm).sort((a,b)=>ts(b)-ts(a));w.forEach(x=>{const m=Math.max(1,parseInt(x.dataset.max||'3',10));x.innerHTML=ordered.slice(0,m).map(card).join('')});const sr=Number(rating)||5,st=Number(total)||40;document.querySelectorAll('.tgd-rating-score').forEach(e=>e.textContent=sr.toFixed(1).replace('.',','));document.querySelectorAll('.tgd-rating-total').forEach(e=>e.textContent=`${st} avis`);document.querySelectorAll('.tgd-rating-number').forEach(e=>e.textContent=String(st))}
function installShell(){
 const links=document.querySelector('.nav-links');
 if(links)links.innerHTML='<li><a href="/convoyage">Convoyage</a></li><li class="nav-dropdown"><a href="/solutions-professionnelles" class="nav-dropdown-toggle">Solutions Pro</a><ul class="nav-dropdown-menu"><li><a href="/solutions-professionnelles">Vue d\'ensemble</a></li><li><a href="/tgd-fleet">TGD Fleet</a></li><li><a href="/tgd-automotive">TGD Automotive</a></li><li><a href="/tgd-digital">TGD Digital</a></li><li><a href="/convoyage-concession">Concessions</a></li></ul></li><li><a href="/chauffeur">Chauffeur</a></li><li><a href="/particuliers">Particuliers</a></li><li><a href="/a-propos">À propos</a></li>';
 const cta=document.querySelector('nav .nav-cta');if(cta){cta.href='/contact';cta.textContent='Confier une mission'}
 const mm=document.querySelector('.mobile-menu');if(mm){const close=mm.querySelector('.mobile-close')?.outerHTML||'<button type="button" class="mobile-close" aria-label="Fermer le menu">✕</button>';mm.innerHTML=close+'<a href="/convoyage">Convoyage</a><a href="/solutions-professionnelles">Solutions Pro</a><div class="tgd-mobile-sub"><a href="/tgd-fleet">Fleet</a><a href="/tgd-automotive">Automotive</a><a href="/tgd-digital">Digital</a></div><a href="/chauffeur">Chauffeur</a><a href="/particuliers">Particuliers</a><a href="/a-propos">À propos</a><a href="/contact" class="btn-primary">Confier une mission</a>';const cb=mm.querySelector('.mobile-close');if(cb)cb.onclick=()=>mm.classList.remove('open');mm.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mm.classList.remove('open')))}
 document.querySelectorAll('.footer-links-list').forEach(f=>{f.innerHTML='<li class="footer-group-label">Services</li><li><a href="/convoyage">Convoyage</a></li><li><a href="/chauffeur">Chauffeur</a></li><li><a href="/mise-en-main">Mise en main</a></li><li><a href="/transport-plateau">Plateau</a></li><li class="footer-sep">·</li><li class="footer-group-label">Professionnels</li><li><a href="/solutions-professionnelles">Solutions Pro</a></li><li><a href="/tgd-fleet">Fleet</a></li><li><a href="/tgd-automotive">Automotive</a></li><li><a href="/tgd-digital">Digital</a></li><li class="footer-sep">·</li><li class="footer-group-label">TGD</li><li><a href="/a-propos">À propos</a></li><li><a href="/etudes-de-cas">Études de cas</a></li><li><a href="/blog">Blog</a></li><li><a href="/faq">FAQ</a></li><li><a href="/contact">Contact</a></li><li><a href="/mentions-legales">Mentions légales</a></li>'});
 if(!document.getElementById('tgd-shell-style')){const s=document.createElement('style');s.id='tgd-shell-style';s.textContent='.nav-links{align-items:center}.nav-dropdown-menu{min-width:230px!important}.nav-dropdown-menu a{text-transform:none!important;letter-spacing:.035em!important;font-size:.72rem!important}.tgd-mobile-sub{display:flex;gap:1rem;flex-wrap:wrap;justify-content:center;margin:-.7rem 0 .1rem}.tgd-mobile-sub a{font-family:Montserrat,sans-serif!important;font-size:.7rem!important;text-transform:uppercase;letter-spacing:.11em;color:#c9a96e!important}.footer-links-list{max-width:1080px!important;margin-left:auto!important;margin-right:auto!important;justify-content:center!important}.footer-group-label{color:#c9a96e!important}.footer-sep{opacity:.35}@media(max-width:900px){.mobile-menu{justify-content:flex-start!important;padding-top:6.2rem!important;gap:1.15rem!important}.mobile-menu>a:not(.btn-primary){font-size:1.4rem!important}.mobile-menu>.btn-primary{margin-top:.25rem!important}}';document.head.appendChild(s)}
}
function upgradeHome(){
 if(!document.body.classList.contains('site-home'))return;
 // Le contenu du hero reste piloté par le HTML pour garantir un message SEO et commercial cohérent dès le premier rendu.
 const pro=document.querySelector('.audience-card[data-audience="professionnel"]');if(pro){pro.href='/solutions-professionnelles';const a=pro.querySelector('strong');if(a)a.textContent='Je gère des véhicules professionnels'}
 if(!document.getElementById('tgd-home-machine-style')){const st=document.createElement('style');st.id='tgd-home-machine-style';st.textContent='.site-home .hero{background:radial-gradient(circle at 72% 32%,rgba(143,156,169,.12),transparent 32%),linear-gradient(135deg,#08090b 0%,#0c0f13 55%,#111820 100%)!important;border-bottom:1px solid rgba(201,169,110,.16)}.site-home .hero-right{background:linear-gradient(145deg,#151b22,#0b0e12)!important}.site-home .hero h1{font-size:clamp(3rem,5vw,5.4rem)!important;max-width:780px}.site-home .hero-desc{font-size:.95rem!important;max-width:650px!important}#tgd-b2b-home-hub{padding:3.1rem 4vw!important;background:#0b0e12;border-bottom:1px solid rgba(201,169,110,.15)}#tgd-b2b-home-hub .inner{max-width:1180px;margin:auto}.b2b-head{display:flex;justify-content:space-between;gap:2rem;align-items:end;margin-bottom:1.5rem}.b2b-head h2{font-family:Cormorant Garamond,serif;font-weight:300;font-size:clamp(2.2rem,4vw,3.7rem);line-height:1.05;margin:0}.b2b-head h2 em{color:#c9a96e}.b2b-head p{max-width:500px;color:#9fa8b1;font-size:.78rem;margin:0}.b2b-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.b2b-card{background:linear-gradient(145deg,#151a20,#0f1318);border:1px solid rgba(157,169,180,.16);padding:1.65rem;text-decoration:none;min-height:205px;position:relative;transition:.25s}.b2b-card:hover{transform:translateY(-3px);border-color:rgba(201,169,110,.55)}.b2b-card .code{font-size:.61rem;letter-spacing:.2em;text-transform:uppercase;color:#8f9aa4}.b2b-card h3{font-family:Cormorant Garamond,serif;font-size:1.85rem;font-weight:400;margin:.7rem 0;color:#f5f0e8}.b2b-card h3 em{color:#c9a96e}.b2b-card p{font-size:.73rem;color:#aeb6bd;line-height:1.65;margin:0 0 1rem}.b2b-card .go{position:absolute;bottom:1.15rem;left:1.65rem;font-size:.62rem;letter-spacing:.13em;text-transform:uppercase;color:#c9a96e}@media(max-width:900px){.b2b-head{display:block}.b2b-head p{margin-top:1rem}.b2b-grid{grid-template-columns:1fr}.site-home .hero h1{font-size:clamp(2.5rem,11vw,4rem)!important}}';document.head.appendChild(st)}
 const router=document.querySelector('.audience-router');if(router&&!document.getElementById('tgd-b2b-home-hub')){const hub=document.createElement('section');hub.id='tgd-b2b-home-hub';hub.innerHTML='<div class="inner"><div class="b2b-head"><div><div class="section-eyebrow">Solutions professionnelles</div><h2>Un opérateur.<br><em>Trois expertises.</em></h2></div><p>Flottes, constructeurs, groupes automobiles et concessions : TGD organise le mouvement, l\'exécution terrain et la preuve de mission.</p></div><div class="b2b-grid"><a class="b2b-card" href="/tgd-fleet"><div class="code">TGD / 01</div><h3>TGD <em>Fleet</em></h3><p>Mouvements de parc, livraisons collaborateurs, restitutions LLD et transferts inter-sites.</p><span class="go">Découvrir Fleet →</span></a><a class="b2b-card" href="/tgd-automotive"><div class="code">TGD / 02</div><h3>TGD <em>Automotive</em></h3><p>Convoyage réseau, livraison client final, mise en main et opérations constructeurs.</p><span class="go">Découvrir Automotive →</span></a><a class="b2b-card" href="/tgd-digital"><div class="code">TGD / 03</div><h3>TGD <em>Digital</em></h3><p>État des lieux, photos, énergie, signatures, PDF et historique de mission.</p><span class="go">Découvrir Digital →</span></a></div></div>';router.insertAdjacentElement('afterend',hub)}
}
async function load(){installShell();upgradeHome();const w=document.querySelectorAll('.tgd-reviews-widget'),d=document.querySelectorAll('.tgd-rating-total,.tgd-rating-number,.tgd-rating-score');if(!w.length&&!d.length)return;try{const r=await fetch('/api/reviews',{cache:'no-store'});if(!r.ok)throw 0;const x=await r.json();render(w,Array.isArray(x.reviews)&&x.reviews.length?x.reviews:FALLBACK,x.rating,x.total)}catch(e){render(w,FALLBACK,5,40)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();
})();

